feedback/models.py
from datetime import datetime
from run import db


class Department(db.Model):
    __tablename__ = 'department'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String)

    def __init__(self, name):
        self.name = name


class Employee(db.Model):
    __tablename__ = 'employee'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String)
    gender = db.Column(db.String)
    mobile = db.Column(db.String)
    address = db.Column(db.String)
    text = db.Column(db.Text)
    c_time = db.Column(db.DateTime)

    departmentid = db.Column(db.Integer, db.ForeignKey('department.id'))
    department = db.relationship('Department', backref=db.backref('employees', lazy='dynamic'))

    def __init__(self, name=None, gender=None,mobile=None, address=None, text=None, c_time=None):
        self.name = name
        self.gender = gender
        self.mobile = mobile
        self.address = address
        self.text = text
        self.c_time = datetime.now()

feedback/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,TextAreaField,SelectField,RadioField


class PostForm(FlaskForm):
    name= StringField('姓名')
    gender = RadioField('性别',choices=[('男','男'),('女','女')])
    mobile=StringField('电话')
    address = StringField('地址')
    departmentid = SelectField('热力公司')
    text = TextAreaField('反馈问题')

class AddDepartment(FlaskForm):
    name = StringField('公司名称')

feedback/__init__.py
from flask import Blueprint

admin = Blueprint('admin',__name__)

from .views import FeedbackPost
from .views import FeedbackList
from .views import FeedbackDel
from .views import FeedbackEdit

fblist=FeedbackList.as_view('emplist')
admin.add_url_rule('/list/',view_func=fblist)
admin.add_url_rule('/list/<int:page>/',view_func=fblist)

admin.add_url_rule('/post/',view_func=FeedbackPost.as_view('post'))
admin.add_url_rule('/del/<int:id>/',view_func=FeedbackDel.as_view(('del')))
admin.add_url_rule('/edit/<int:id>/',view_func=FeedbackEdit.as_view('edit'))

feedback/views.py
from datetime import datetime
from flask import render_template,request,redirect,url_for
from flask.views import MethodView
from .forms import PostForm
from .models import db,Employee,Department



class FeedbackPost(MethodView):
    def get(self):

        form = PostForm()
        form.departmentid.choices=[(d.id,d.name) for d in Department.query.all()]

        return render_template('feedback-post.html', form=form)
    def post(self):
        form=PostForm(request.form)
        emp = Employee()
        form.populate_obj(emp)
        db.session.add(emp)
        db.session.commit()
        return redirect(url_for('admin.emplist'))

class FeedbackList(MethodView):
    def get(self,page=1):
        kw=request.args.get('kw')

        form = Employee.query.filter(Employee.name.contains('%{}%'.format(kw))).paginate(page,per_page=10) if kw else Employee.query.paginate(page,per_page=10)
        return render_template('feedback_list.html',form=form)



class FeedbackDel(MethodView):
    def get(self,id=None):
        emp = Employee.query.get(id)
        db.session.delete(emp)
        db.session.commit()
        return redirect(url_for('admin.emplist'))

class FeedbackEdit(MethodView):
    def get(self,id=None):
        emp = Employee.query.get(id)
        form = PostForm(request.form,obj=emp)
        form.departmentid.choices = [(d.id, d.name) for d in Department.query.all()]
        return render_template('feedback-post.html',form=form)

    def post(self,id=None):
        form = PostForm(request.form)
        emp = Employee.query.get(id)
        form.populate_obj(emp)
        db.session.add(emp)
        db.session.commit()
        return redirect(url_for('admin.emplist'))

templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <script src="https://cdn.bootcss.com/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdn.bootcss.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <title>问题反馈系统</title>
</head>
<body>
<div class="container">
    <div class="row">
        <nav class="navbar navbar-default" role="navigation">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">问题反馈系统</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse navbar-ex1-collapse">
                <ul class="nav navbar-nav">
                    <li class="active"><a href="{{ url_for('admin.emplist') }}">反馈列表</a></li>
                    <li><a href="{{ url_for('admin.post') }}">添加反馈</a></li>
                </ul>

                <ul class="nav navbar-nav navbar-right">
                    <li><a href="#">Link</a></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">管理 <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a href="#">Action</a></li>
                            <li><a href="#">Another action</a></li>
                            <li><a href="#">Something else here</a></li>
                            <li><a href="#">Separated link</a></li>
                        </ul>
                    </li>
                </ul>
            </div><!-- /.navbar-collapse -->
        </nav>
    </div>
    {% block main_context %}

    {% endblock %}
    <div class="row">
        <div class="well text-center">
            &copy; 派森软件工作室  <a href="#">www.paisensoft.com</a>
        </div>
    </div>

</div>
</body>
</html>

templates/feedback-post.html
{% extends 'base.html' %}
    {% block main_context %}
        <div class="row">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4>添加反馈问题</h4>
                </div>
                <div class="panel-body">
                    <form action="#" method="post" role="form" class="form-horizontal">

                        <div class="form-group">
                            {{ form.name.label(class="col-md-2 control-label") }}
                            <div class="col-md-6">
                                {{ form.name(class="form-control") }}
                            </div>
                        </div>
                        <div class="form-group">
                            {{ form.gender.label(class="col-md-2 control-label") }}
                            <div class="col-md-6">
                                {% for gender in form.gender %}
                                    {{ gender }}{{ gender.label }}
                                {% endfor %}

                            </div>
                        </div>
                        <div class="form-group">
                            {{ form.mobile.label(class="col-md-2 control-label") }}
                            <div class="col-md-6">
                                {{ form.mobile(class="form-control") }}
                            </div>
                        </div>
                        <div class="form-group">
                            {{ form.address.label(class="col-md-2 control-label") }}
                            <div class="col-md-6">
                                {{ form.address(class="form-control") }}
                            </div>
                        </div>
                        <div class="form-group">
                            {{ form.departmentid.label(class="col-md-2 control-label") }}
                            <div class="col-md-6">
                                {{ form.departmentid(class="form-control") }}
                            </div>
                        </div>


                        <div class="form-group">
                            {{ form.text.label(class="col-md-2 control-label") }}
                            <div class="col-md-6">
                                {{ form.text(class="form-control ",rows="10",cols="20") }}
                            </div>
                        </div>


                        <div class="col-md-offset-2">
                            <button type="submit" class="btn btn-primary">提交</button>
                            <button type="reset" class="btn btn-primary">重置</button>
                            <button type="button" class="btn btn-default">返回列表</button>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    {% endblock %}

templates/feedback_list.html
{% extends 'base.html' %}
{% import 'helper.html' as helper %}
{% block main_context %}
    <div class="row">
    <div class="panel panel-default">
    <div class="panel-heading">

            <div class="col-md-2"><h4>问题列表</h4></div>
        <form class="panel-heading" role="search" method="get">
                    <div class="form-group col-md-6">
                        <input type="text" name="kw" class="form-control" placeholder="Search">
                    </div>
                    <button type="submit" class="btn btn-default">搜索</button>
                </form>
    </div>
        <div class="panel-body">
            <table class="table table-hover " >
                <thead>
                <tr>
                    <th>#</th>
                    <th>姓名</th>
                    <th>性别</th>
                    <th>电话</th>
                    <th>地址</th>
                    <th>热力公司</th>
                    <th>反馈日期</th>
                    <th>操作</th>

                </tr>
                </thead>
                <tbody>
                {% for emp in form.items %}
                <tr>
                    <td>{{ emp.id }}</td>
                    <td>{{ emp.name }}</td>
                    <td>{{ emp.gender }}</td>
                    <td>{{ emp.mobile }}</td>
                    <td>{{ emp.address }}</td>
                    <td>{{ emp.department.name }}</td>
                    <td>{{ emp.c_time.strftime('%Y-%m-%d %H-%M') }}</td>
                    <td>
                        <a href=""><i class="fa fa-search fa-md"></i></a>
                        <a href="{{ url_for('admin.edit',id=emp.id) }}"><i class="fa fa-pencil fa-md"></i></a>
                        <a href="{{ url_for('admin.del',id=emp.id) }}"><i class="fa fa-trash fa-md"></i></a>
                    </td>
                </tr>
                {% endfor %}


                </tbody>
            </table>
        </div>
        {{ helper.render_paginate(form,'admin.emplist') }}

    </div>
    </div>
{% endblock %}

templates/helper.html
{% macro render_paginate(paginate,endpoint) %}
    <div class="text-center">
        <ul class="pagination pagination-md">
            <li><a href="{{ url_for(endpoint,page=1) }}">首页</a></li>
            {% if paginate.has_prev %}
                <li><a href="{{ url_for(endpoint,page=paginate.prev_num) }}">«</a></li>
            {% endif %}


            {% for page in paginate.iter_pages() %}
                {% if page %}
                    {% if page != paginate.page %}
                        <li><a href="{{ url_for(endpoint,page=page) }}">{{ page }}</a></li>
                    {% else %}
                        <li class="active"><a href="#">{{ page }}</a></li>
                    {% endif %}

                {% endif %}

            {% endfor %}


            {% if paginate.has_next %}
                <li><a href="{{ url_for(endpoint,page=paginate.next_num) }}">»</a></li>
            {% endif %}

            <li><a href="{{ url_for(endpoint,page=paginate.pages) }}">末页</a></li>
        </ul>
    </div>

{% endmacro %}